objects/Player__c.object
<CustomObject>
    <description>Person who plays soccer</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is active?</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PlayerServices.cls
public class PlayerServices {
    
    public static Map<String, List<Player__c>> groupActiveByStatus (List<Player__c> listOfPlayers){
        Map<String, List<Player__c>> playersMap = new Map<String, List<Player__c>>();
        List<Player__c> active = new List<Player__c>();
        List<Player__c> inactive = new List<Player__c>();


        for(Player__c player: listOfPlayers){
            if(player.IsActive__c){
                active.add(player);
            }else{
                inactive.add(player);
            }
        }
        playersMap.put('active', active);
        playersMap.put('inactive', inactive);
        
        return playersMap;
    }
}